// Generated by CoffeeScript 1.9.1
var addMessage, addScore, barLeftDirection, calculateFrames, checkAnswer, gup, moveBar, pauseGame, pickRandomFrame, playGame, playing, randomFrame, stopBar, tempScore, updateScore;

randomFrame = 24;

tempScore = 0;

addScore = function(number) {
  if (number > 0) {
    return tempScore = tempScore + number;
  }
};

updateScore = function() {
  var score;
  if (tempScore > 0) {
    tempScore = tempScore(-1);
    score = score + 1;
    return $score.html("<i class='fa fa-money'></i> " + score);
  }
};

setInterval(updateScore, 30);

playing = false;

playGame = function() {
  playing = true;
  randomFrame = pickRandomFrame(frameRange[1]);
  $("message2").text("The answer is: " + randomFrame);
  return moveBar();
};

pauseGame = function() {
  playing = false;
  return stopBar();
};

barLeftDirection = false;

moveBar = function() {
  if (playing) {
    soundclick.play();
    if (barLeftDirection) {
      barLeftDirection = false;
      return $("#bar").animate({
        width: "100%"
      }, calculateFrames(randomFrame, fps), "linear", moveBar);
    } else {
      barLeftDirection = true;
      return $("#bar").animate({
        width: "0%"
      }, calculateFrames(randomFrame, fps), "linear", moveBar);
    }
  }
};

stopBar = function() {
  return $("#bar").stop(true, true);
};

addMessage = function(classtitle, message) {
  var listNum, maxUp, messageBox;
  maxUp = 5;
  $("#messageHolder").prepend("<li class='span6 message " + classtitle + "'><p>" + message + "</p></li>");
  messageBox = $("#messageHolder li");
  messageBox.first().hide().fadeIn("slow");
  listNum = messageBox.length;
  if (listNum > maxUp) {
    return messageBox.last().fadeOut("slow", function() {
      return $(this).remove();;
    });
  }
};

calculateFrames = function(frame, framesPerSecond) {
  var singleFrame;
  singleFrame = 1000 / framesPerSecond;
  return frame * singleFrame;
};

pickRandomFrame = function(range) {
  return Math.floor(Math.random() * (range[1] - range[0] + 1)) + range[0];
};

checkAnswer = function(answer, number) {
  var numInt;
  numInt = parseInt(answer);
  if (numInt === !numInt) {
    return false;
  } else {
    return numInt = number - numInt;
  }
};

gup = function(name) {
  var regex, regexS, results;
  name = name.replace(/[\[]/, "\\\[").replace(/[\]]/, "\\\]");
  regexS = "[\\?&]" + name + "=([^&#]*)";
  regex = new RegExp(regexS);
  results = regex.exec(window.location.href);
  if (results) {
    return results[1];
  }
};
